project:
  type: website
  output-dir: docs

resources: 
  - robots.txt

website:
  title: "Park Youngsam Homepage"
  site-url: "https://youngsampk.github.io/labor_stat/"
  open-graph: true
  description: "노동 경제 사회 통계 정책 고용 노사관계 문제를 다루는 박영삼의 웹페이지"
  navbar:
    left:
      - text: "News | Column"
        file: index.qmd
      - text: "Notes"
        href: notes.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "About"
        file: about.qmd
    right:
      - icon: github
        href: https://github.com/
      - icon: facebook
        href: https://facebook.com
#########################
# You can ignore this part in the first step
      - icon: rss
        href: index.xml
      - text: Blogger
        href: http://yspark1968.blogspot.com/
#########################
format:
  html:
    theme: 
      - cosmo
      - theme1.scss
#    css: mystyles.css
    date-format: "YYYY-MM-dd"         # 2025-08-15
    crossref:
      fig-title: "그림"   # (default is "Figure")
      tbl-title: "표"    # (default is "Table")
      fig-prefix: "그림"   # (default is "Figure")
      tbl-prefix: "표"    # (default is "Table")
    include-in-header: includes/verify.html
    include-after-body: gtag.js
editor: source